package org.mybatis.generator.domain;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.mybatisGenerator.annotation.ColumnGeneratorDoc;
import org.mybatis.mybatisGenerator.annotation.TableGeneratorDoc;

/**
 * Database Table Remarks:用于存储动态的评论
 * table name:Comments
 * @author lixin
 * @date 2024-03-06 18:10:37
 * modelBaseRecordClassGenerated
 */
@TableGeneratorDoc(remark = "用于存储动态的评论",name = "Comments")
public class Comments implements Serializable {
    /**
     * Database Column Remarks:评论唯一标识符（主键）
     * Actual Column Name: comment_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "comment_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "评论唯一标识符（主键）",isPrimaryKey = true,isAuto = true)
    private Integer commentId;

    /**
     * Database Column Remarks:评论用户的ID
     * Actual Column Name: user_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "user_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "评论用户的ID")
    private Integer userId;

    /**
     * Database Column Remarks:被评论的动态ID
     * Actual Column Name: post_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "post_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "被评论的动态ID")
    private Integer postId;

    /**
     * Database Column Remarks:评论时间
     * Actual Column Name: timestamp, JDBC Type: 93, Nullable: false, Length: 19, Scale: 0, Identity: false
     * this column typeName: TIMESTAMP
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "TIMESTAMP",name = "timestamp", jdbcType = 93, isNull = false, length = 19, Scale = 0, Identity = false, type = 1, remark = "评论时间")
    private Date timestamp;

    /**
     * Database Column Remarks:评论内容
     * Actual Column Name: content, JDBC Type: -1, Nullable: false, Length: 65535, Scale: 0, Identity: false
     * this column typeName: LONGVARCHAR
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "LONGVARCHAR",name = "content", jdbcType = -1, isNull = false, length = 65535, Scale = 0, Identity = false, type = 1, remark = "评论内容")
    private String content;

    /**
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comments.comment_id
     *
     * @return the value of Comments.comment_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comments.comment_id
     *
     * @param commentId the value for Comments.comment_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comments.user_id
     *
     * @return the value of Comments.user_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comments.user_id
     *
     * @param userId the value for Comments.user_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comments.post_id
     *
     * @return the value of Comments.post_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comments.post_id
     *
     * @param postId the value for Comments.post_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comments.timestamp
     *
     * @return the value of Comments.timestamp
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comments.timestamp
     *
     * @param timestamp the value for Comments.timestamp
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Comments.content
     *
     * @return the value of Comments.content
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Comments.content
     *
     * @param content the value for Comments.content
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}