package org.mybatis.generator.domain;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.mybatisGenerator.annotation.ColumnGeneratorDoc;
import org.mybatis.mybatisGenerator.annotation.TableGeneratorDoc;

/**
 * Database Table Remarks:用于存储用户之间的好友关系
 * table name:Friendships
 * @author lixin
 * @date 2024-03-06 18:10:37
 * modelBaseRecordClassGenerated
 */
@TableGeneratorDoc(remark = "用于存储用户之间的好友关系",name = "Friendships")
public class Friendships implements Serializable {
    /**
     * Database Column Remarks:好友关系唯一标识符（主键）
     * Actual Column Name: friendship_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "friendship_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "好友关系唯一标识符（主键）",isPrimaryKey = true,isAuto = true)
    private Integer friendshipId;

    /**
     * Database Column Remarks:用户ID
     * Actual Column Name: user_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "user_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "用户ID")
    private Integer userId;

    /**
     * Database Column Remarks:好友ID
     * Actual Column Name: friend_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "friend_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "好友ID")
    private Integer friendId;

    /**
     * Database Column Remarks:建立好友关系的时间
     * Actual Column Name: timestamp, JDBC Type: 93, Nullable: true, Length: 19, Scale: 0, Identity: false
     * this column typeName: TIMESTAMP
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "TIMESTAMP",name = "timestamp", jdbcType = 93, isNull = true, length = 19, Scale = 0, Identity = false, type = 1, remark = "建立好友关系的时间")
    private Date timestamp;

    /**
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Friendships.friendship_id
     *
     * @return the value of Friendships.friendship_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getFriendshipId() {
        return friendshipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Friendships.friendship_id
     *
     * @param friendshipId the value for Friendships.friendship_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setFriendshipId(Integer friendshipId) {
        this.friendshipId = friendshipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Friendships.user_id
     *
     * @return the value of Friendships.user_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Friendships.user_id
     *
     * @param userId the value for Friendships.user_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Friendships.friend_id
     *
     * @return the value of Friendships.friend_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Friendships.friend_id
     *
     * @param friendId the value for Friendships.friend_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Friendships.timestamp
     *
     * @return the value of Friendships.timestamp
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Friendships.timestamp
     *
     * @param timestamp the value for Friendships.timestamp
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}