package org.mybatis.generator.domain;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.mybatisGenerator.annotation.ColumnGeneratorDoc;
import org.mybatis.mybatisGenerator.annotation.TableGeneratorDoc;

/**
 * Database Table Remarks:群组成员表
 * table name:group_member
 * @author lixin
 * @date 2024-03-06 18:10:37
 * modelBaseRecordClassGenerated
 */
@TableGeneratorDoc(remark = "群组成员表",name = "group_member")
public class Groupmember implements Serializable {
    /**
     * Database Column Remarks:成员ID，主键
     * Actual Column Name: id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: true
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = true, type = 1, remark = "成员ID，主键",isPrimaryKey = true,isAuto = true)
    private Integer id;

    /**
     * Database Column Remarks:所属群组ID
     * Actual Column Name: group_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "group_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "所属群组ID")
    private Integer groupId;

    /**
     * Database Column Remarks:成员的用户ID
     * Actual Column Name: user_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "user_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "成员的用户ID")
    private Integer userId;

    /**
     * Database Column Remarks:是否是群组管理员
     * Actual Column Name: is_admin, JDBC Type: -6, Nullable: true, Length: 3, Scale: 0, Identity: false
     * this column typeName: TINYINT
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "TINYINT",name = "is_admin", jdbcType = -6, isNull = true, length = 3, Scale = 0, Identity = false, type = 1, remark = "是否是群组管理员")
    private Byte isAdmin;

    /**
     * Database Column Remarks:成员加入群组的时间
     * Actual Column Name: join_time, JDBC Type: 93, Nullable: true, Length: 19, Scale: 0, Identity: false
     * this column typeName: TIMESTAMP
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "TIMESTAMP",name = "join_time", jdbcType = 93, isNull = true, length = 19, Scale = 0, Identity = false, type = 1, remark = "成员加入群组的时间")
    private Date joinTime;

    /**
     * Actual Column Name: boolean_test, JDBC Type: -5, Nullable: true, Length: 19, Scale: 0, Identity: false
     * this column typeName: BIGINT
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "BIGINT",name = "boolean_test", jdbcType = -5, isNull = true, length = 19, Scale = 0, Identity = false, type = 1, remark = "")
    private Long booleanTest;

    /**
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.id
     *
     * @return the value of group_member.id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.id
     *
     * @param id the value for group_member.id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.group_id
     *
     * @return the value of group_member.group_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.group_id
     *
     * @param groupId the value for group_member.group_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.user_id
     *
     * @return the value of group_member.user_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.user_id
     *
     * @param userId the value for group_member.user_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.is_admin
     *
     * @return the value of group_member.is_admin
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Byte getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.is_admin
     *
     * @param isAdmin the value for group_member.is_admin
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setIsAdmin(Byte isAdmin) {
        this.isAdmin = isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.join_time
     *
     * @return the value of group_member.join_time
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.join_time
     *
     * @param joinTime the value for group_member.join_time
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.boolean_test
     *
     * @return the value of group_member.boolean_test
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Long getBooleanTest() {
        return booleanTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.boolean_test
     *
     * @param booleanTest the value for group_member.boolean_test
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setBooleanTest(Long booleanTest) {
        this.booleanTest = booleanTest;
    }
}