package org.mybatis.generator.domain;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.mybatisGenerator.annotation.ColumnGeneratorDoc;
import org.mybatis.mybatisGenerator.annotation.TableGeneratorDoc;

/**
 * Database Table Remarks:群聊消息表
 * table name:group_chat_message
 * @author lixin
 * @date 2024-03-06 18:10:37
 * modelBaseRecordClassGenerated
 */
@TableGeneratorDoc(remark = "群聊消息表",name = "group_chat_message")
public class Groupchatmessage implements Serializable {
    /**
     * Database Column Remarks:消息ID
     * Actual Column Name: id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: true
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = true, type = 1, remark = "消息ID",isPrimaryKey = true,isAuto = true)
    private Integer id;

    /**
     * Database Column Remarks:群聊ID
     * Actual Column Name: group_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "group_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "群聊ID")
    private Integer groupId;

    /**
     * Database Column Remarks:发送者ID
     * Actual Column Name: sender_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "sender_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "发送者ID")
    private Integer senderId;

    /**
     * Database Column Remarks:消息类型: 1-文本, 2-图片, 3-音频, 4-视频, ...
     * Actual Column Name: message_type, JDBC Type: -6, Nullable: false, Length: 3, Scale: 0, Identity: false
     * this column typeName: TINYINT
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "TINYINT",name = "message_type", jdbcType = -6, isNull = false, length = 3, Scale = 0, Identity = false, type = 1, remark = "消息类型: 1-文本, 2-图片, 3-音频, 4-视频, ...")
    private Byte messageType;

    /**
     * Database Column Remarks:发送时间
     * Actual Column Name: send_time, JDBC Type: 93, Nullable: true, Length: 19, Scale: 0, Identity: false
     * this column typeName: TIMESTAMP
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "TIMESTAMP",name = "send_time", jdbcType = 93, isNull = true, length = 19, Scale = 0, Identity = false, type = 1, remark = "发送时间")
    private Date sendTime;

    /**
     * Database Column Remarks:消息内容
     * Actual Column Name: content, JDBC Type: -1, Nullable: false, Length: 65535, Scale: 0, Identity: false
     * this column typeName: LONGVARCHAR
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "LONGVARCHAR",name = "content", jdbcType = -1, isNull = false, length = 65535, Scale = 0, Identity = false, type = 1, remark = "消息内容")
    private String content;

    /**
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_chat_message.id
     *
     * @return the value of group_chat_message.id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_chat_message.id
     *
     * @param id the value for group_chat_message.id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_chat_message.group_id
     *
     * @return the value of group_chat_message.group_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_chat_message.group_id
     *
     * @param groupId the value for group_chat_message.group_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_chat_message.sender_id
     *
     * @return the value of group_chat_message.sender_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_chat_message.sender_id
     *
     * @param senderId the value for group_chat_message.sender_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_chat_message.message_type
     *
     * @return the value of group_chat_message.message_type
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Byte getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_chat_message.message_type
     *
     * @param messageType the value for group_chat_message.message_type
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setMessageType(Byte messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_chat_message.send_time
     *
     * @return the value of group_chat_message.send_time
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_chat_message.send_time
     *
     * @param sendTime the value for group_chat_message.send_time
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_chat_message.content
     *
     * @return the value of group_chat_message.content
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_chat_message.content
     *
     * @param content the value for group_chat_message.content
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}