package org.mybatis.generator.domain;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.mybatisGenerator.annotation.ColumnGeneratorDoc;
import org.mybatis.mybatisGenerator.annotation.TableGeneratorDoc;

/**
 * Database Table Remarks:用于存储动态的点赞记录
 * table name:Likes
 * @author lixin
 * @date 2024-03-06 18:10:37
 * modelBaseRecordClassGenerated
 */
@TableGeneratorDoc(remark = "用于存储动态的点赞记录",name = "Likes")
public class Likes implements Serializable {
    /**
     * Database Column Remarks:点赞记录唯一标识符（主键）
     * Actual Column Name: like_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "like_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "点赞记录唯一标识符（主键）",isPrimaryKey = true,isAuto = true)
    private Integer likeId;

    /**
     * Database Column Remarks:点赞用户的ID
     * Actual Column Name: user_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "user_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "点赞用户的ID")
    private Integer userId;

    /**
     * Database Column Remarks:被点赞的动态ID
     * Actual Column Name: post_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "post_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "被点赞的动态ID")
    private Integer postId;

    /**
     * Database Column Remarks:点赞时间
     * Actual Column Name: timestamp, JDBC Type: 93, Nullable: false, Length: 19, Scale: 0, Identity: false
     * this column typeName: TIMESTAMP
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "TIMESTAMP",name = "timestamp", jdbcType = 93, isNull = false, length = 19, Scale = 0, Identity = false, type = 1, remark = "点赞时间")
    private Date timestamp;

    /**
     * Database Column Remarks:0生效 1取消 -1删除
     * Actual Column Name: status, JDBC Type: -6, Nullable: true, Length: 3, Scale: 0, Identity: false
     * this column typeName: TINYINT
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "TINYINT",name = "status", jdbcType = -6, isNull = true, length = 3, Scale = 0, Identity = false, type = 1, remark = "0生效 1取消 -1删除")
    private Byte status;

    /**
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Likes.like_id
     *
     * @return the value of Likes.like_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Likes.like_id
     *
     * @param likeId the value for Likes.like_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Likes.user_id
     *
     * @return the value of Likes.user_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Likes.user_id
     *
     * @param userId the value for Likes.user_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Likes.post_id
     *
     * @return the value of Likes.post_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Likes.post_id
     *
     * @param postId the value for Likes.post_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Likes.timestamp
     *
     * @return the value of Likes.timestamp
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Likes.timestamp
     *
     * @param timestamp the value for Likes.timestamp
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Likes.status
     *
     * @return the value of Likes.status
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Likes.status
     *
     * @param status the value for Likes.status
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}