package org.mybatis.generator.domain;

import java.io.Serializable;
import java.util.Date;
import org.mybatis.mybatisGenerator.annotation.ColumnGeneratorDoc;
import org.mybatis.mybatisGenerator.annotation.TableGeneratorDoc;

/**
 * Database Table Remarks:用于存储用户的动态内容
 * table name:Posts
 * @author lixin
 * @date 2024-03-06 18:10:37
 * modelBaseRecordClassGenerated
 */
@TableGeneratorDoc(remark = "用于存储用户的动态内容",name = "Posts")
public class Posts implements Serializable {
    /**
     * Database Column Remarks:动态唯一标识符（主键）
     * Actual Column Name: post_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "post_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "动态唯一标识符（主键）",isPrimaryKey = true,isAuto = true)
    private Integer postId;

    /**
     * Database Column Remarks:发布动态的用户ID
     * Actual Column Name: user_id, JDBC Type: 4, Nullable: false, Length: 10, Scale: 0, Identity: false
     * this column typeName: INTEGER
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "INTEGER",name = "user_id", jdbcType = 4, isNull = false, length = 10, Scale = 0, Identity = false, type = 1, remark = "发布动态的用户ID")
    private Integer userId;

    /**
     * Database Column Remarks:动态发布时间
     * Actual Column Name: timestamp, JDBC Type: 93, Nullable: false, Length: 19, Scale: 0, Identity: false
     * this column typeName: TIMESTAMP
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "TIMESTAMP",name = "timestamp", jdbcType = 93, isNull = false, length = 19, Scale = 0, Identity = false, type = 1, remark = "动态发布时间")
    private Date timestamp;

    /**
     * Actual Column Name: image_url, JDBC Type: 12, Nullable: true, Length: 255, Scale: 0, Identity: false
     * this column typeName: VARCHAR
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "VARCHAR",name = "image_url", jdbcType = 12, isNull = true, length = 255, Scale = 0, Identity = false, type = 1, remark = "")
    private String imageUrl;

    /**
     * Database Column Remarks:动态内容
     * Actual Column Name: content, JDBC Type: -1, Nullable: false, Length: 65535, Scale: 0, Identity: false
     * this column typeName: LONGVARCHAR
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    @ColumnGeneratorDoc(typeName = "LONGVARCHAR",name = "content", jdbcType = -1, isNull = false, length = 65535, Scale = 0, Identity = false, type = 1, remark = "动态内容")
    private String content;

    /**
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Posts.post_id
     *
     * @return the value of Posts.post_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Posts.post_id
     *
     * @param postId the value for Posts.post_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Posts.user_id
     *
     * @return the value of Posts.user_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Posts.user_id
     *
     * @param userId the value for Posts.user_id
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Posts.timestamp
     *
     * @return the value of Posts.timestamp
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Posts.timestamp
     *
     * @param timestamp the value for Posts.timestamp
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Posts.image_url
     *
     * @return the value of Posts.image_url
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Posts.image_url
     *
     * @param imageUrl the value for Posts.image_url
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Posts.content
     *
     * @return the value of Posts.content
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Posts.content
     *
     * @param content the value for Posts.content
     *
     * @mbg.generated 2024-03-06 18:10:37
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}